### ISSUE TITLE
A toolbox for web extension development: @holoflows/kit (licenced AGPLv3.0)

### ISSUE THREAD

**Issue by Jack-Works** [fregante/Awesome-WebExtensions#45]
https://github.com/DimensionDev/Holoflows-Kit

domain: Dom Operation, Tab manipulation

this package is heavily used in our extension https://github.com/DimensionDev/Maskbook

I wish you can take a look and add it to the list maybe

**Comment by fregante** [comment]
I think the API is too broad (includes both generic DOM utilities and extension utilities) and a bit awkward to use (everything is a class)

Also the documentation isn’t clear enough on what each piece does and how to use it
