### ISSUE TITLE
Add @types/firefox-webext-browser ?

### ISSUE THREAD

**Issue by jsmnbom** [fregante/Awesome-WebExtensions#52]
Hi

I'm the author of https://www.npmjs.com/package/@types/firefox-webext-browser. It's been very useful for my development of webextensions in typescript. It's especially useful combined with webextension-polyfill for cross browser extension development.
The types are generated mostly automatically (needs a couple of fixes each firefox version) by https://github.com/jsmnbom/definitelytyped-firefox-webext-browser. A new updated version for firefox 78 should be out as soon as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45360 gets merged.

**Comment by jsmnbom** [comment]
@fregante I see that you've upvoted. I'll take that as that you do want it included. I'll make a PR soon, but I'm unsure what category it should fall under?

**Comment by fregante** [comment]
You can place it right under `mozilla/webextension-polyfill` since it's related to it.
