### ISSUE TITLE
[Tool] web-ext-deploy

### ISSUE THREAD

**Issue by avi12** [fregante/Awesome-WebExtensions#56]
I made a Puppeteer-based tool [web-ext-deploy](https://github.com/avi12/web-ext-deploy) that supports Chrome Web Store, Firefox Addons, Opera Addons, and Edge Addons, and since it's using Puppeteer - it's highly scalable
I'd love it if you could add it to the list

**Comment by fregante** [comment]
Thanks, this is interesting, but it appears to be cookie-based? Don’t they expire? That makes it undesirable for automated setups since it will end up not working every so often

**Comment by avi12** [comment]
Since I don't update my extensions too often, I haven't had the chance to try it after a long period
For now, the developer can run `web-ext-deploy --get-cookies=store-name`
In the future, I might make it automatic, so if the cookie is invalid, a Puppeteer session will start, such that the required login pages will open automatically

**Comment by fregante** [comment]
But:

- that won’t work on CI
- there are already API-based solutions that aren’t affected by this problem
- your method will break when the stores change their HTML or internal endpoints

I think only Microsoft Store submissions aren’t covered by other tools, but Microsoft also has an API for it that should be used instead https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-add-on-submissions

I don’t think I should include a fragile tool in this list

**Comment by avi12** [comment]
> * that won’t work on CI

Indeed, I did not consider this use-case since I've never used CI myself
> * there are already API-based solutions that aren’t affected by this problem

I'd love it if you could link me to official publishing APIs for Firefox and Opera, as I couldn't find them myself

> * your method will break when the stores change their HTML or internal endpoints

Indeed, though I don't think the stores' HTML will change that much
Even if they will, I will update the code accordingly

> I think only Microsoft Store submissions aren’t covered by other tools, but Microsoft also has an API for it that should be used instead https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-add-on-submissions

The resource doesn't seem relevant to Edge extensions at first glance

**Comment by avi12** [comment]
One of the biggest reasons to use my module for Firefox deployment is to upload the ZIP source code

**Comment by avi12** [comment]
In the past couple of months, I updated my tool to use the [Edge Publish API v1.1](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1) and [Firefox Submission API](https://blog.mozilla.org/addons/2022/03/17/new-api-for-submitting-and-updating-add-ons/)
As for the Opera store, I started [mimicking the API calls](https://github.com/avi12/web-ext-deploy/blob/4ae1f623ae1d1afcccaeff4b4227a942177e3930/src/stores/opera/opera-deploy.ts) that the store is doing for various interactions so that it doesn't launch a costly headless Playwright instance
