### ISSUE TITLE
ExtPay

### ISSUE THREAD

**Issue by Glench** [fregante/Awesome-WebExtensions#58]
I wanted to see if the library I wrote, [ExtPay.js](https://github.com/Glench/ExtPay) would be a good fit for this repo.

It's a library/service that makes it easy for developers to accept payments in their extensions without needing to run their own server backend. It's open-source, works across browsers, and is free to use (only taking a small fee when someone actually pays). I made it to use in my own extensions and wanted to provide this service for others after the Chrome store shut down payments.

Please let me know if you'd be willing to include my library!

**Comment by fregante** [comment]
Sounds great! Feel free to send a PR
